# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    # Base

    config.vm.box = "ubuntu/focal64"
    config.vm.synced_folder ".", "/vagrant"

    # Provider
    config.vm.provider "virtualbox" do |vb|
        vb.name = "DIA-NN"
        vb.memory = 10240
        vb.cpus = 2
    end

    # Network
    config.vm.hostname = "diann"
    config.vm.network "private_network", ip: "192.168.1.2"

    # Setup
    config.vm.provision "ansible_local" do |ansible|
        ansible.playbook = "playbook.yml"
        ansible.install_mode = "default"
        ansible.version = "latest"
    end
end