# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/impish64"
  config.vm.network "forwarded_port", guest: 8000, host: 8080
  
  config.vm.provider :virtualbox do |vb|
    vb.memory = 2048
  end
end
