# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.hostname = ""
  config.vm.network "forwarded_port", guest:22, host:2022, id:"ssh"
  config.vm.network "private_network", ip: "192.168.56.1"
end
