# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    # Base
    config.vm.box = "ubuntu/jammy64"
    config.vm.synced_folder ".", "/vagrant"

    # Provider
    config.vm.provider "virtualbox" do |vb|
        vb.name = "ubuntu"
        vb.memory = 2048
        vb.cpus = 1
    end

    # Network
    config.vm.hostname = "gdkk-vb1.jp.genedata.com"
    config.vm.network "private_network", ip: "192.168.56.2"

    # Provision
    config.vm.provision "ansible_local" do |ansible|
        ansible.playbook = "playbook.yml"
        ansible.install_mode = "default"
        ansible.version = "latest"
    end
end
